
package server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransferService", targetNamespace = "http://server/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransferService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://server/TransferService/sendInternalRequest", output = "http://server/TransferService/sendInternalResponse")
    public void sendInternal(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    String arg1,
            @WebParam(name = "arg2", partName = "arg2")
                    String arg2,
            @WebParam(name = "arg3", partName = "arg3")
                    int arg3,
            @WebParam(name = "arg4", partName = "arg4")
                    String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://server/TransferService/sendExternalRequest", output = "http://server/TransferService/sendExternalResponse")
    public void sendExternal(
            @WebParam(name = "arg0", partName = "arg0")
                    String arg0,
            @WebParam(name = "arg1", partName = "arg1")
                    String arg1,
            @WebParam(name = "arg2", partName = "arg2")
                    String arg2,
            @WebParam(name = "arg3", partName = "arg3")
                    int arg3,
            @WebParam(name = "arg4", partName = "arg4")
                    String arg4,
            @WebParam(name = "arg5", partName = "arg5")
                    String arg5);

    /**
     * 
     * @return
     *     returns server.AccountUrlList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server/TransferService/getExternalAccountsNameRequest", output = "http://server/TransferService/getExternalAccountsNameResponse")
    public AccountUrlList getExternalAccountsName();

}
