
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransferServiceImplService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/transfers?wsdl")
public class TransferServiceImplService
    extends Service
{

    private final static URL TRANSFERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSFERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TRANSFERSERVICEIMPLSERVICE_QNAME = new QName("http://server/", "TransferServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/transfers?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSFERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TRANSFERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TransferServiceImplService() {
        super(__getWsdlLocation(), TRANSFERSERVICEIMPLSERVICE_QNAME);
    }

    public TransferServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSFERSERVICEIMPLSERVICE_QNAME, features);
    }

    public TransferServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TRANSFERSERVICEIMPLSERVICE_QNAME);
    }

    public TransferServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSFERSERVICEIMPLSERVICE_QNAME, features);
    }

    public TransferServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransferServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransferService
     */
    @WebEndpoint(name = "TransferServiceImplPort")
    public TransferService getTransferServiceImplPort() {
        return super.getPort(new QName("http://server/", "TransferServiceImplPort"), TransferService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransferService
     */
    @WebEndpoint(name = "TransferServiceImplPort")
    public TransferService getTransferServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "TransferServiceImplPort"), TransferService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSFERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TRANSFERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TRANSFERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
